# Generated by Django 2.0.9 on 2018-12-11 01:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0001_initial'),
        ('depots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('last_free_day', models.DateField()),
                ('reference_number', models.TextField(max_length=11)),
                ('container_number', models.TextField(max_length=11)),
                ('move_type', models.TextField(choices=[('inland', 'INLAND'), ('port', 'PORT')], max_length=6)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('depot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='depots.Depot')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendors.Vendor')),
            ],
            options={
                'ordering': ['last_free_day'],
            },
        ),
    ]
